clear

echo "                                                                         "
echo "                                                                         "
echo "                                                                         "
echo "                                     ▄▄▄      ▓█████▄  ███▄ ▄███▓ ▄▄▄     ▄▄▄█████▓"
echo "                                    ▒████▄    ▒██▀ ██▌▓██▒▀█▀ ██▒▒████▄   ▓  ██▒ ▓▒"
echo "                                    ▒██  ▀█▄  ░██   █▌▓██    ▓██░▒██  ▀█▄ ▒ ▓██░ ▒░"
echo "                                    ░██▄▄▄▄██ ░▓█▄   ▌▒██    ▒██ ░██▄▄▄▄██░ ▓██▓ ░ "
echo "                                     ▓█   ▓██▒░▒████▓ ▒██▒   ░██▒ ▓█   ▓██▒ ▒██▒ ░ "
echo "                                     ▒▒   ▓▒█░ ▒▒▓  ▒ ░ ▒░   ░  ░ ▒▒   ▓▒█░ ▒ ░░ "
echo "                                     ▒   ▒▒ ░ ░ ▒  ▒ ░  ░      ░  ▒   ▒▒ ░   ░  "
echo "                                    ░   ▒    ░ ░  ░ ░      ░     ░   ▒    ░   "
echo "                                        ░  ░   ░           ░         ░  ░   "
echo "                                             ░     "





python3 /home/ubuntu/Desktop/proxit2/BTC.py &
python3 /home/ubuntu/Desktop/proxit2/ETH.py &
python3 /home/ubuntu/Desktop/proxit2/BNB.py &
python3 /home/ubuntu/Desktop/proxit2/XRP.py &
python3 /home/ubuntu/Desktop/proxit2/ADA.py &
python3 /home/ubuntu/Desktop/proxit2/SOL.py &
python3 /home/ubuntu/Desktop/proxit2/DOGE.py &
python3 /home/ubuntu/Desktop/proxit2/MATIC.py &
python3 /home/ubuntu/Desktop/proxit2/DOT.py &
python3 /home/ubuntu/Desktop/proxit2/DAI.py &
python3 /home/ubuntu/Desktop/proxit2/SHIB.py &
python3 /home/ubuntu/Desktop/proxit2/TRX.py &
python3 /home/ubuntu/Desktop/proxit2/AVAX.py &
python3 /home/ubuntu/Desktop/proxit2/UNI.py &
python3 /home/ubuntu/Desktop/proxit2/WBTC.py &
python3 /home/ubuntu/Desktop/proxit2/LEO.py &
python3 /home/ubuntu/Desktop/proxit2/LTC.py &
python3 /home/ubuntu/Desktop/proxit2/ATOM.py &
python3 /home/ubuntu/Desktop/proxit2/LINK.py &
python3 /home/ubuntu/Desktop/proxit2/ETC.py &
python3 /home/ubuntu/Desktop/proxit2/XLM.py &
python3 /home/ubuntu/Desktop/proxit2/FTT.py &
python3 /home/ubuntu/Desktop/proxit2/NEAR.py &
python3 /home/ubuntu/Desktop/proxit2/CRO.py &
python3 /home/ubuntu/Desktop/proxit2/XMR.py &
python3 /home/ubuntu/Desktop/proxit2/ALGO.py &
python3 /home/ubuntu/Desktop/proxit2/BCH.py &
python3 /home/ubuntu/Desktop/proxit2/LUNC.py &
python3 /home/ubuntu/Desktop/proxit2/QNT.py &
python3 /home/ubuntu/Desktop/proxit2/FLOW.py &
python3 /home/ubuntu/Desktop/proxit2/VET.py &
python3 /home/ubuntu/Desktop/proxit2/TON.py &
python3 /home/ubuntu/Desktop/proxit2/APE.py &
python3 /home/ubuntu/Desktop/proxit2/FIL.py &
python3 /home/ubuntu/Desktop/proxit2/ICP.py &
python3 /home/ubuntu/Desktop/proxit2/HBAR.py &
python3 /home/ubuntu/Desktop/proxit2/EGLD.py &
python3 /home/ubuntu/Desktop/proxit2/XTZ.py &
python3 /home/ubuntu/Desktop/proxit2/MANA.py &
python3 /home/ubuntu/Desktop/proxit2/SAND.py &
python3 /home/ubuntu/Desktop/proxit2/CHZ.py &
python3 /home/ubuntu/Desktop/proxit2/EOS.py &
python3 /home/ubuntu/Desktop/proxit2/AAVE.py &
python3 /home/ubuntu/Desktop/proxit2/THETA.py &
python3 /home/ubuntu/Desktop/proxit2/AXS.py &
python3 /home/ubuntu/Desktop/proxit2/USDP.py &
python3 /home/ubuntu/Desktop/proxit2/OKB.py &
python3 /home/ubuntu/Desktop/proxit2/BSV.py &
python3 /home/ubuntu/Desktop/proxit2/TUSD.py &
python3 /home/ubuntu/Desktop/proxit2/MKR.py &
python3 /home/ubuntu/Desktop/proxit2/KCS.py &
python3 /home/ubuntu/Desktop/proxit2/ZEC.py &
python3 /home/ubuntu/Desktop/proxit2/USDD.py &
python3 /home/ubuntu/Desktop/proxit2/HT.py &
python3 /home/ubuntu/Desktop/proxit2/XEC.py &
python3 /home/ubuntu/Desktop/proxit2/MIOTA.py &
python3 /home/ubuntu/Desktop/proxit2/BTT.py &
python3 /home/ubuntu/Desktop/proxit2/USDN.py &
python3 /home/ubuntu/Desktop/proxit2/CAKE.py &
python3 /home/ubuntu/Desktop/proxit2/GRT.py &
python3 /home/ubuntu/Desktop/proxit2/NEO.py &
python3 /home/ubuntu/Desktop/proxit2/HNT.py &
python3 /home/ubuntu/Desktop/proxit2/KLAY.py &
python3 /home/ubuntu/Desktop/proxit2/FTM.py &
python3 /home/ubuntu/Desktop/proxit2/PAXG.py &
python3 /home/ubuntu/Desktop/proxit2/SNX.py &
python3 /home/ubuntu/Desktop/proxit2/RUNE.py &
python3 /home/ubuntu/Desktop/proxit2/NEXO.py &
python3 /home/ubuntu/Desktop/proxit2/GT.py &
python3 /home/ubuntu/Desktop/proxit2/DASH.py &
python3 /home/ubuntu/Desktop/proxit2/CRV.py &
python3 /home/ubuntu/Desktop/proxit2/BAT.py &
python3 /home/ubuntu/Desktop/proxit2/ENJ.py &
python3 /home/ubuntu/Desktop/proxit2/LDO.py &
python3 /home/ubuntu/Desktop/proxit2/STX.py &
python3 /home/ubuntu/Desktop/proxit2/KAVA.py &
python3 /home/ubuntu/Desktop/proxit2/COMP.py &
python3 /home/ubuntu/Desktop/proxit2/ZIL.py &
python3 /home/ubuntu/Desktop/proxit2/FEI.py &
python3 /home/ubuntu/Desktop/proxit2/RVN.py &
python3 /home/ubuntu/Desktop/proxit2/MINA.py &
python3 /home/ubuntu/Desktop/proxit2/WAVES.py &
python3 /home/ubuntu/Desktop/proxit2/XDC.py &
python3 /home/ubuntu/Desktop/proxit2/USDTC.py &
python3 /home/ubuntu/Desktop/proxit2/GMT.py &
python3 /home/ubuntu/Desktop/proxit2/TWT.py &
python3 /home/ubuntu/Desktop/proxit2/LRC.py &
python3 /home/ubuntu/Desktop/proxit2/DCR.py &
python3 /home/ubuntu/Desktop/proxit2/CVX.py &
python3 /home/ubuntu/Desktop/proxit2/CSPR.py &
python3 /home/ubuntu/Desktop/proxit2/XEM.py &
python3 /home/ubuntu/Desktop/proxit2/KSM.py &
python3 /home/ubuntu/Desktop/proxit2/CELO.py &
python3 /home/ubuntu/Desktop/proxit2/BTG.py &
python3 /home/ubuntu/Desktop/proxit2/ENS.py &
python3 /home/ubuntu/Desktop/proxit2/1INCH.py &
python3 /home/ubuntu/Desktop/proxit2/HOT.py &
python3 /home/ubuntu/Desktop/proxit2/LUNA.py &
python3 /home/ubuntu/Desktop/proxit2/RSR.py &
python3 /home/ubuntu/Desktop/proxit2/BNX.py &
python3 /home/ubuntu/Desktop/proxit2/GUSD.py &
python3 /home/ubuntu/Desktop/proxit2/ROSE.py &
python3 /home/ubuntu/Desktop/proxit2/YFI.py &
python3 /home/ubuntu/Desktop/proxit2/QTUM.py &
python3 /home/ubuntu/Desktop/proxit2/AR.py &
python3 /home/ubuntu/Desktop/proxit2/ANKR.py &
python3 /home/ubuntu/Desktop/proxit2/GNO.py &
python3 /home/ubuntu/Desktop/proxit2/GALA.py &
python3 /home/ubuntu/Desktop/proxit2/TFUEL.py &
python3 /home/ubuntu/Desktop/proxit2/KDA.py &
python3 /home/ubuntu/Desktop/proxit2/IOTX.py &
python3 /home/ubuntu/Desktop/proxit2/GLM.py &
python3 /home/ubuntu/Desktop/proxit2/BTRST.py &
python3 /home/ubuntu/Desktop/proxit2/JST.py &
python3 /home/ubuntu/Desktop/proxit2/CEL.py &
python3 /home/ubuntu/Desktop/proxit2/POLY.py &
python3 /home/ubuntu/Desktop/proxit2/ONE.py &
python3 /home/ubuntu/Desktop/proxit2/HIVE.py &
python3 /home/ubuntu/Desktop/proxit2/OMG.py &
python3 /home/ubuntu/Desktop/proxit2/LPT.py &
python3 /home/ubuntu/Desktop/proxit2/ZRX.py &
python3 /home/ubuntu/Desktop/proxit2/BAL.py &
python3 /home/ubuntu/Desktop/proxit2/FLUX.py &
python3 /home/ubuntu/Desktop/proxit2/IOST.py &
python3 /home/ubuntu/Desktop/proxit2/ICX.py &
python3 /home/ubuntu/Desktop/proxit2/BORA.py &
python3 /home/ubuntu/Desktop/proxit2/AMP.py &
python3 /home/ubuntu/Desktop/proxit2/XYM.py &
python3 /home/ubuntu/Desktop/proxit2/SRM.py &
python3 /home/ubuntu/Desktop/proxit2/KNC.py &
python3 /home/ubuntu/Desktop/proxit2/ONT.py &
python3 /home/ubuntu/Desktop/proxit2/OP.py &
python3 /home/ubuntu/Desktop/proxit2/GLMR.py &
python3 /home/ubuntu/Desktop/proxit2/CHSB.py &
python3 /home/ubuntu/Desktop/proxit2/STORJ.py &
python3 /home/ubuntu/Desktop/proxit2/WAXP.py &
python3 /home/ubuntu/Desktop/proxit2/SC.py &
python3 /home/ubuntu/Desktop/proxit2/WOO.py &
python3 /home/ubuntu/Desktop/proxit2/ZEN.py &
python3 /home/ubuntu/Desktop/proxit2/XCH.py &
python3 /home/ubuntu/Desktop/proxit2/SXP.py &
python3 /home/ubuntu/Desktop/proxit2/SUSHI.py &
python3 /home/ubuntu/Desktop/proxit2/IMX.py &
python3 /home/ubuntu/Desktop/proxit2/MXC.py &
python3 /home/ubuntu/Desktop/proxit2/AUDIO.py &
python3 /home/ubuntu/Desktop/proxit2/NFT.py &
python3 /home/ubuntu/Desktop/proxit2/UMA.py &
python3 /home/ubuntu/Desktop/proxit2/PLA.py &
python3 /home/ubuntu/Desktop/proxit2/SKL.py &
python3 /home/ubuntu/Desktop/proxit2/ABBC.py &
python3 /home/ubuntu/Desktop/proxit2/SCRT.py &
python3 /home/ubuntu/Desktop/proxit2/SLP.py &
python3 /home/ubuntu/Desktop/proxit2/DGB.py &
python3 /home/ubuntu/Desktop/proxit2/ELON.py &
python3 /home/ubuntu/Desktop/proxit2/INJ.py &
python3 /home/ubuntu/Desktop/proxit2/VGX.py &
python3 /home/ubuntu/Desktop/proxit2/CKB.py &
python3 /home/ubuntu/Desktop/proxit2/CVC.py &
python3 /home/ubuntu/Desktop/proxit2/LSK.py &
python3 /home/ubuntu/Desktop/proxit2/VLX.py &
python3 /home/ubuntu/Desktop/proxit2/PUNDIX.py &
python3 /home/ubuntu/Desktop/proxit2/COTI.py &
python3 /home/ubuntu/Desktop/proxit2/KEEP.py &
python3 /home/ubuntu/Desktop/proxit2/DAO.py &
python3 /home/ubuntu/Desktop/proxit2/REN.py &
python3 /home/ubuntu/Desktop/proxit2/MED.py &
python3 /home/ubuntu/Desktop/proxit2/RNDR.py &
python3 /home/ubuntu/Desktop/proxit2/CEEK.py &
python3 /home/ubuntu/Desktop/proxit2/REEF.py &
python3 /home/ubuntu/Desktop/proxit2/EWT.py &
python3 /home/ubuntu/Desktop/proxit2/PEOPLE.py &
python3 /home/ubuntu/Desktop/proxit2/BTCST.py &
python3 /home/ubuntu/Desktop/proxit2/WIN.py &
python3 /home/ubuntu/Desktop/proxit2/NU.py &
python3 /home/ubuntu/Desktop/proxit2/CELR.py &
python3 /home/ubuntu/Desktop/proxit2/SYS.py &
python3 /home/ubuntu/Desktop/proxit2/ONG.py &
python3 /home/ubuntu/Desktop/proxit2/XNO.py &
python3 /home/ubuntu/Desktop/proxit2/REQ.py &
python3 /home/ubuntu/Desktop/proxit2/DAG.py &
python3 /home/ubuntu/Desktop/proxit2/ORBS.py &
python3 /home/ubuntu/Desktop/proxit2/SPELL.py &
python3 /home/ubuntu/Desktop/proxit2/RLC.py &
python3 /home/ubuntu/Desktop/proxit2/OCEAN.py &
python3 /home/ubuntu/Desktop/proxit2/API3.py &
python3 /home/ubuntu/Desktop/proxit2/SNT.py &
python3 /home/ubuntu/Desktop/proxit2/TRIBE.py &
python3 /home/ubuntu/Desktop/proxit2/ARDR.py &
python3 /home/ubuntu/Desktop/proxit2/PYR.py &
python3 /home/ubuntu/Desktop/proxit2/FX.py &
python3 /home/ubuntu/Desktop/proxit2/UOS.py &
python3 /home/ubuntu/Desktop/proxit2/POWER.py &
python3 /home/ubuntu/Desktop/proxit2/ACA.py &
python3 /home/ubuntu/Desktop/proxit2/PROM.py &
python3 /home/ubuntu/Desktop/proxit2/DENT.py &
python3 /home/ubuntu/Desktop/proxit2/CHR.py &
python3 /home/ubuntu/Desktop/proxit2/MX.py &
python3 /home/ubuntu/Desktop/proxit2/%launcher%


